# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sridhar Mocherla
title: Software Engineer
email: sridhar.mocherla@outlook.com
website: https://sridharmocherla.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: SridharMocherla
github_username: srmocher
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: sridharmocherla
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
 - title: Bazel Remote Caching Article
   icon: fas fa-rocket
   url: https://medium.com/@sridharmocherla/leveraging-bazel-remote-caching-and-execution-for-cross-platform-builds-mac-linux-1956e6f3cb22
 - title: Bazel-Kotlin VSCode Extension
   icon: fas fa-code
   url: https://marketplace.visualstudio.com/items?itemName=Brex.bazel-kotlin

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/sridhar.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Sridhar. I'm a staff software engineer specializing in developer productivity, build systems, and polyglot development at scale. I have deep expertise in Bazel, CI/CD optimization, and have made significant open-source contributions to the JVM/Kotlin ecosystem.

  My work spans across multiple languages (Go, Kotlin, TypeScript, Python) and focuses on solving complex infrastructure challenges in large monorepos. I'm passionate about creating tools that make developers more productive.

  Note: If you're a recruiter hiring for a company from the US, please reach out only if you sponsor work visas. It will save my time and yours. :)

content:
  - title: Open Source Contributions # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Bazel-Kotlin Language Server
        link: https://marketplace.visualstudio.com/items?itemName=Brex.bazel-kotlin
        sub_title: VSCode Extension
        caption: Published on Visual Studio Marketplace
        description: |
          Created a VSCode extension that adds Bazel support to the Kotlin language server, enabling better IDE integration for Kotlin projects built with Bazel. This extension improves developer experience by providing proper language support, navigation, and error reporting in Bazel-managed Kotlin codebases.

      - layout: left
        title: Gradle Dependencies in Bazel
        link: https://github.com/bazel-contrib/rules_jvm_external/pull/1357
        sub_title: rules_jvm_external Contribution
        caption: Merged PR to bazel-contrib
        description: |
          Added Gradle support to resolve JVM dependencies with Bazel, specifically targeting improved Kotlin Multiplatform support. This contribution enables teams to leverage Gradle's dependency resolution while maintaining Bazel's build performance and reproducibility benefits.

      - layout: left
        title: Bazel Remote Caching Guide
        link: https://medium.com/@sridharmocherla/leveraging-bazel-remote-caching-and-execution-for-cross-platform-builds-mac-linux-1956e6f3cb22
        sub_title: Technical Article
        caption: Published on Medium
        description: |
          Authored a comprehensive guide on leveraging Bazel remote caching for JVM projects in hybrid mode (remote execution and local execution). The article covers practical implementation strategies for cross-platform builds on Mac/Linux environments.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Brex
        link: brex.com
        sub_title: Senior Software Engineer/Staff Software Engineer
        caption: March 2022 - current
        description: |
          **Build Systems & Developer Productivity:**
          - Architected Bazel-based polyglot development environment supporting Go, Kotlin, TypeScript, Python, and Protobuf in a large monorepo
          - Reduced cloud infrastructure costs by an order of magnitude through optimized build and caching strategies
          - Built Cloud Development Environments to accelerate developer onboarding and productivity
          - Created custom Bazel rules for GraphQL supergraph composition and subgraph validation to prevent API breaking changes
          
          **GraphQL & Performance:**
          - Migrated from Apollo Gateway to Apollo Router (Rust implementation) improving GraphQL API performance by 30%
          - Led federated GraphQL architecture improvements and developer experience enhancements
          - Extensive work with JVM frameworks including Micronaut for microservice development
          
          **CI/CD & Infrastructure:**
          - Optimized Buildkite CI/CD pipelines significantly reducing build times
          - Integrated GitOps with FluxCD on Kubernetes to accelerate microservice development
          - Managed AWS infrastructure and container orchestration for scalable deployment pipelines

      - layout: left
        title: LinkedIn
        link: linkedin.com
        # link_text: boringcompany.com
        sub_title: Senior Software Engineer
        caption: April 2020 - February 2022
        quote: >
          We all need people who will give us feedback. That’s how we improve
        description: | # this will include new lines to allow paragraphs
          **Developer Experience & Documentation:**
          - Improved documentation discoverability across LinkedIn's engineering organization
          - Built real-time feedback systems enabling engineers to provide input on tooling and processes
          - Enhanced support experiences for LinkedIn's extensive suite of internal developer tools
          - Focused on developer productivity improvements and streamlined engineering workflows

      - layout: left
        title: Cruise
        link: getcruise.com
        # link_text: boringcompany.com
        sub_title: Senior Software Engineer
        caption: June 2018 - April 2020
        quote: >
          Humans are bad at driving cars and machines can do better.
        description: | # this will include new lines to allow paragraphs
          **Large-Scale Distributed Systems & Build Infrastructure:**
          - Built large-scale distributed systems enabling testing simulations on large cloud workers for autonomous vehicle development
          - Architected systems allowing engineers to iterate rapidly on ML models and autonomous driving features
          - Maintained C++/Python monorepo with Bazel build system, including custom rules and build performance optimization
          - Implemented Remote Build Execution (RBE) for improved build performance and scalability
          - Led CI migration from CircleCI to Buildkite significantly improving build performance and reliability

      - layout: left
        title: University of Arizona
        link: as.arizona.edu
        # link_text: boringcompany.com
        sub_title: Research Assistant
        caption: August 2016 - May 2018
        quote: >
          Democratizing astronomy knowledge through powerful visualizations.
        description: | # this will include new lines to allow paragraphs
          I worked at the Steward Observatory under Dr. Chris Impey on building tools that were powered by machine learning to allow beginners to grasp astronomy and its concepts.

      - layout: left
        title: Microsoft
        link: microsoft.com
        # link_text: boringcompany.com
        sub_title: Software Engineer/Service Engineer
        caption: July 2014 - May 2016
        quote: >
          Working on enterprise B2B legacy codebase was a learning experience right out of college.
        description: | # this will include new lines to allow paragraphs
          Right out of college, I joined a rotational program at Microsoft that allowed me to work in 2 different roles (Service Engineer/Software Engineer) that allowed me exposure to enterprise-scale infrastructure and services in the Universal Store Team. I worked on improving the reliability and availability of the OEM application suite through disaster recovery automation across datacenters. As an SWE, I built a number of features that enabled hybrid connectivity (cloud/on-premise) for B2B message processing for orders between Microsoft and OEM/volume licensing partners.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Chaitanya Bharathi Institute of Technology (CBIT)
        caption: 2010 - 2014
        sub_title: BE Computer Science & Engineering
        quote: >
          Established in 1979, CBIT is one of the top private institutes for engineering in the southern state of Telangana, India.
        description: | # this will include new lines to allow paragraphs
          Learned the ropes of basic CS, did some projects and used it as a platform for my entry in the industry.

      - layout: left
        title: University of Arizona
        caption: 2016 - 2018
        sub_title: MS Computer Science
        quote: >
          Established in 1885, The University of Arizona is one of the premier public universities in the Southwest United States and offers degrees in upto 300 majors.
        description: | # this will include new lines to allow paragraphs
          During my time at UofA, I took courses across a broad array of CS subjects, while also taking advanced research oriented courses in graph theory.

  - title: Technical Skills & Expertise
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Build Systems & Developer Productivity:**
      - Bazel (Expert): Custom rules, Remote Build Execution (RBE), polyglot builds, performance optimization
      - CI/CD: Buildkite, CircleCI, GitHub Actions, build performance optimization
      - Developer Tooling: VSCode extensions, language server protocols, IDE integrations

      **Programming Languages & Frameworks:**
      - **Go**: Microservices, distributed systems, performance-critical applications
      - **Kotlin**: Multiplatform development, JVM ecosystem
      - **TypeScript/JavaScript**: Full-stack web development, GraphQL, Node.js
      - **Python**: Build tooling, automation, data processing, ML pipelines
      - **Rust**: GraphQL federation (Apollo Router), systems programming
      - **Protobuf**: Schema design, code generation, cross-language serialization

      **Infrastructure & Cloud:**
      - **AWS**: ECS, EKS, Lambda, S3, infrastructure automation
      - **Kubernetes**: GitOps with FluxCD, microservice orchestration
      - **GraphQL**: Federated architecture, Apollo Gateway/Router, schema composition
      - **JVM Ecosystem**: Micronaut, Gradle, dependency management

      **Specialized Areas:**
      - Large monorepo management and tooling
      - Remote caching and distributed build systems
      - Polyglot development environments
      - Developer experience and productivity optimization

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interest in software engineering some of my other interests and hobbies are:
      - Hiking
      - Soccer
      - Board games

      My favorite place in my travels so far (guess where it is?)
      ![Trees](./images/banff.jpeg "Lake Louise")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
